package xyz.nardone.aide.largescale.constant;

public enum EOutboxEventType {
    DONOR_CREATED,
    ORGANIZATION_CREATED,
    ORGANIZATION_SUSPENDED,
    CAMPAIGN_CREATED,
    DONATION_CREATED_GRAPH,
    DONATION_CREATED_DASHBOARD,
    DONATION_CONCLUDED_DASHBOARD,
    CAMPAIGN_STATUS_CHANGED
}
