spring.main.banner-mode=off

# MongoDB config
spring.mongodb.database=mongofundme
spring.mongodb.uri=mongodb://localhost:27017,localhost:27018,localhost:27019/?replicaSet=rs0&readPreference=primary&readConcernLevel=majority&w=majority&wtimeoutMS=5000

# JWT config
gs.app.jwtSecret=sdflksdfjlk(fbfubyefb/647hhgiorbfiviuefiobuf837f93v9290g803jvjfi
gs.app.jwtExpirationMs=20000000

# Neo4j config
spring.neo4j.uri=neo4j://127.0.0.1:7687
spring.neo4j.authentication.username=neo4j
spring.neo4j.authentication.password=qwe15001qwe
spring.data.neo4j.database=neo4j
